[package]
name = "derive-const-serialize"
version = "0.1.0"
edition = "2021"
description = "A macro to derive const serialize"
license = "MIT/Apache-2.0"
repository = "https://github.com/ealmloff/const-serialize"
authors = ["Evan Almloff"]
keywords = ["const", "serialize", "derive"]

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0.86"

[lib]
proc-macro = true
